name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Ensure pnpm is available
        run: npm install -g pnpm

      - name: Install dependencies (pnpm / npm / yarn)
        run: |
          set -e
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            npm install
          fi

      - name: Build project
        env:
          NODE_ENV: production
        run: |
          set -e
          # Try the common build script variants (npm/pnpm/yarn)
          npm run build || pnpm run build || yarn build

          # If the project exports static files (Next.js), try export scripts.
          # next export produces an "out" directory by default.
          npm run export || pnpm run export || yarn export || true

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # default Next.js export directory is "out"
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
